### PR TITLE
chore(update.sh): check presence of the required tools

### PR DESCRIPTION
**Pull request by igiona**
Might be helpful to someone (younger me 🤣)

### CODE REVIEW

**Comment by plaes** [comment]
At current state, chiptool is actually expected to be checked out next to the nrf-pac repository:
https://github.com/embassy-rs/nrf-pac/blob/f37e86a6c79ab745ccd308b1f16973bf57b8bc82/update.sh#L10

**Comment by igiona** [comment]
> At current state, chiptool is actually expected to be checked out next to the nrf-pac repository:
> https://github.com/embassy-rs/nrf-pac/blob/f37e86a6c79ab745ccd308b1f16973bf57b8bc82/update.sh#L10

Interesting, it does work for me (or at least it doesn't fail because of "chiptool not found)
I'll look into this

**Comment by Dirbaio** [comment]
sorry I didn't see this PR, for some reason I wasn't watching the repo so I didn't get notified. I've done this in 8eae25c10f53d3b8b4bbaf004ea85831da242e4e

(also note this pac doesn't use `form`)

**Comment by igiona** [comment]
Perfect 👍

**Pull request closed without merging**
